channel_list:
  dingtalk:
    settings: {}
  discord:
    settings: {}
  feishu:
    settings: {}
  irc:
    settings: {}
  line:
    settings: {}
  maixcam:
    settings: {}
  matrix:
    settings: {}
  onebot:
    settings: {}
  pico:
    settings:
      token: {}
  qq:
    settings: {}
  slack:
    settings: {}
  telegram:
    settings:
      token: 
  wecom:
    settings: {}
  weixin:
    settings: {}
  whatsapp:
    settings: {}
model_list:
  gemini-audio:0:
    api_keys:
      - {}
  gemini-lite:0:
    api_keys:
      - {}
      - {}
  gemma-31b:0:
    api_keys:
      - {}
      - {}
  gemma-a4b:0:
    api_keys:
      - {}
      - {}
  groq:0:
    api_keys:
      - {}
  nvidia:0:
    api_keys:
      - {}
  openrouter:0:
    api_keys:
      - {}
web:
  brave: {}
  tavily: {}
  gemini: {}
  perplexity: {}
  glm_search: {}
  baidu_search: {}
skills:
  registries: {}
