channel_list:
  telegram:
    settings:
      token: {}
model_list:
  gemini-audio:0:
    api_keys:
      - {}
  gemini-lite:0:
    api_keys:
      - {}
      - {}
  gemma-31b:0:
    api_keys:
      - {}
      - {}
  gemma-a4b:0:
    api_keys:
      - {}
      - {}
  groq:0:
    api_keys:
      - {}
  nvidia:0:
    api_keys:
      - {}
  openrouter:0:
    api_keys:
      - {}
web:
  brave: {}
  tavily: {}
  gemini: {}
  perplexity: {}
  glm_search: {}
skills:
  registries: {}
